### ISSUE TITLE
windows uuid

### ISSUE THREAD

**Issue by cucurbita** [postwait/node-libuuid#9]
Hello, needing a cross-platform uuidv4 generator-backend too; yesterday, I took some time, and here what I came up with:

https://gist.github.com/cucurbita/bfc86cc936216db7c54f
https://gist.github.com/cucurbita/2c72227f25d6d5adb599

if it helps, passing the buck, cheers!

**Comment by postwait** [comment]
Do you mind submitting a pull request with these changes?

**Comment by cucurbita** [comment]
Hello, 

that's only and still a draft, it needs yet more serious work and real-time testing ; meaning recursively generate thousands of them to see what's the best approach ; random or machine-default, if folks have windows machines to test ; returns welcome. 

Best.

**Comment by cucurbita** [comment]
@postwait do you know who's the actual maintainer of libuuid ? do you have any contact? else I am tempted to fork ; but I would prefer not.
